version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/projeto
    ports:
      - "7777:8000"
    image: app:latest
    container_name: django_container
    command: sh -c "chmod +x /projeto/start.sh && /projeto/start.sh"
    environment:
      - STATIC_ROOT=/projeto/static/
